# this can be any network from the timm library
arch: resnet18
pretrained: true

# resize images to this size
image_size: 64
# crop to this fraction of image_size
crop_size: 0.94

# optimizer settings
lr: 0.01
momentum: 0.9
nesterov: false
batch_size: 128

# scheduler settings
gamma: 0.96

{%- if cookiecutter.augmentation == "True" %}
aug_prob: 0.75
strong_aug: true

{%- endif %}