# this can be any network from the timm library
arch: resnet18
pretrained: true

# resize images to this size on the fly
image_size: {{ cookiecutter.image_size }}
# crop to this fraction of image_size
crop_size: 0.8

# optimizer settings
lr: 0.001
batch_size: 64

# scheduler settings
gamma: 0.96

{%- if cookiecutter.augmentation == "True" %}
aug_prob: 0.1
strong_aug: false

{%- endif %}
