# this can be any network from the timm library
arch: resnet18
pretrained: true
dropout_rate: 0.5

# resize images to this size on the fly
image_size: {{ cookiecutter.image_size }}
# crop to this fraction of image_size
crop_size: 0.8

# optimizer settings
optim: sgd
lr: 0.001
weight_decay: 0.01
batch_size: 32

# scheduler settings
gamma: 0.96

{%- if cookiecutter.augmentation == "True" %}
aug_prob: 0.1
strong_aug: false
max_cutout: 0

{%- endif %}
