# prompt for the first frame of the animation
begin_prompt: "bladerunneresque cityscape, child's crayon doodle"
# prompt for the last frame of the animation
end_prompt: "bladerunneresque cityscape, award winning photorealism, cinematic composition, trending on artstation, featured on pixiv, 8k, matte painting, unreal engine 5, epic lighting, masterpiece, in sharp focus, vivid colors"

# seed for the random number generator - change this for different output
seed: 1
# number of denoising steps
num_inference_steps: 40
# use higher guidance scale to generate images that are closely linked to the prompt
guidance_scale: 6

# number of frames to generate using stable diffusion
num_frames: {{ cookiecutter.num_frames }}
frame_height: {{ cookiecutter.frame_height }}
frame_width: {{ cookiecutter.frame_width }}
frame_rate: 24

# this specifies how many interpolated frames to insert (recursively)
# using pretrained film_net model
interp_recursion: 2