# FPN, Unet, Unet++, DeepLabV3, Unet3D, Hybrid23D
arch: Hybrid23D
backbone: efficientnet-b3
pretrained: true
res_units: 2

num_slices: 5
multi_slice_label: false
val_interval: 5

# optimizer settings
optim: adam
lr: 5.0e-4
min_lr: 1.0e-6
dropout: 0.2
weight_decay: 1.0e-6
batch_size: 1

# scheduler settings
restart_epoch: {'FPN': 5, 'Unet3D': 100, 'Hybrid23D': 5}
gamma: 0.98

# data augmentation
aug_prob: 0.6
strong_aug: true
max_cutout: 10
tta_flip_dims: [[]]
#tta_flip_dims: [[], [2], [3], [2, 3]]

# 3D settings

# height, width
train_roi: 224
test_roi: 224
# depth
train_depth: 80
test_depth: 80
sliding_win_overlap: 0.25